driver:
  name: vagrant

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  data_bags_path: "test/integration/data_bags"
  environments_path: "test/integration/environment"
  solo_rb:
    environment: default

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[csync2::default]
    attributes:
